### ISSUE TITLE
How open new window on click event ?

### ISSUE THREAD

**Issue by hubertstruminski** [Tristan971/EasyFXML#41]
Hi,

I have problem with opennng second fxml file on click event in first main component.
I invoke method easyFxml.load(component) but windows doesn't open.

`@Controller
public class MainWindowController implements FxmlController {

    @Autowired
    private NewTaxWindowComponent newTaxWindowComponent;

    @Autowired
    private EasyFxml easyFxml;

    @FXML
    void onNewTaxMenuItemAction(ActionEvent event) {
        easyFxml.load(newTaxWindowComponent);
    }
    }

@Controller
public class NewTaxWindowController implements FxmlController {

//    @Autowired
//    private TaxRepository taxRepository;

    @Autowired
    private EasyFxml easyFxml;

    @Autowired
    private MainWindowUiManager mainWindowUiManager;

    @Autowired
    private NewTaxWindowComponent newTaxWindowComponent;

    @Override
    public void initialize() {
        Scene scene = mainWindowUiManager.getScene(newTaxWindowComponent);
        Stage stage = new Stage();
        stage.setScene(scene);
        mainWindowUiManager.startGui(stage);
    }
    }
`

When I click button is invoked method onNewTaxMenuItemAction(ActionEvent event). The flow is redirected to NewTaxWindowController when is invoked method initialize(). If I think well I should invoke there startGui() method but this also doesn't work.

Additionally: When I pass to autwire TaxRepository class which is annotated @Repository, field returns null. Can you explain why is that ?

**Comment by hubertstruminski** [comment]
i try with onNodeLoaded but in variable Pane getScene() is null. Anywhere I try get scene I get null.
After is easyffxml.load(component) invoked I am redirect to initialize method in second controller but there scene is too null. Can you explain me where should I invoke startGui() method ?

**Comment by Tristan971** [comment]
I see you closed it, but for reference, `#startGui` is automatically called here https://github.com/Tristan971/EasyFXML/blob/master/easyfxml/src/main/java/moe/tristan/easyfxml/FxApplication.java#L77

The idea is:

JavaFX starts up, and provides a `Stage` (the main stage), and we pass this to the Spring bean of type `FxUiManager` to do whatever it pleases with it

This has 2 advantages:
- JavaFX now has delegated flow control to spring (as the ui manager is invoked through `context#getBean`)
- the UI manager can be agnostic of the initialisation, and just patiently wait for `startGui` to be called once both JavaFX and Spring are ready

As for autowiring, there's a subtlety going on:
- Spring calls the class constructor (and should follow all the usual Spring logic), at which point Spring dependency injection is done
- JavaFX calls `#initialize` once all the UI elements are ready (and injected)

This means that you have access to Spring components before the UI is ready, but the UI components cannot be invoked before `initialize` is called by JavaFX

In practice you want to have a pattern of:
1. Constructor for Spring DI strictly, and nothing else (since all `@FXML` fields will still be null at this point)
2. `Initialize` for UI stuff, and nothing else (this runs on the main JavaFX thread too, so any code there will freeze the UI during execution)
3. A third method, called from `initialize` (whether directly or not) which does things "live" (ie when the user sees it)
